### ISSUE TITLE
Your templates are not in a valid format

### ISSUE THREAD

**Issue by peersbio** [zezutom/NiFiByExample#1]
Hi Tomas,

Thanks for the great tutorial. Unfortunately, your NiFi templatescannot be imported to Nifi. I tried both Nifi 0.7.1 and Nifi 1.1.1, I got the error ” The specified template is not in a valid format”. Could you check if the templates are working?

Thanks a lot

Andy

**Comment by zezutom** [comment]
Hi Andy,
Thanks for raising this issue. The problem was that the links pointed to a formatted view on github, rather than the actual raw xml. I've corrected the links in README and verified I could upload the templates in NiFi 0.7.1, 1.0.0 and 1.1.1
